const DEFAULT_PAGE_NO = 0;
const DEFAULT_PAGE_SIZE = 10;
const DEFAULT_SORT_BY = 'id';
const DEFAULT_SORT_DIR = 'asc';
const DEFAULT_STATUS = ['ACTIVE'];
const DEFAULT_SEARCH_NEAR_BY = true;
const TEST_USER_LOCATION_LATITUDE = 10.771019171437418;
const TEST_USER_LOCATION_LONGITUDE = 106.69153962582232;

export {
  DEFAULT_PAGE_NO,
  DEFAULT_PAGE_SIZE,
  DEFAULT_SORT_BY,
  DEFAULT_SORT_DIR,
  DEFAULT_STATUS,
  DEFAULT_SEARCH_NEAR_BY,
  TEST_USER_LOCATION_LATITUDE,
  TEST_USER_LOCATION_LONGITUDE,
};
