const RESTAURANT_DETAIL_ROUTE = '/restaurant-detail';
const RESTAURANT_ROUTE = '/restaurant';
const USER_ROUTE = '/user';
const USER_PASS_ROUTE = '/user-pass';
const USER_FAVOR_ROUTE = '/user-favorite';
const SIGN_IN_ROUTE = '/signin';
const SIGN_UP_ROUTE = '/signup';
const CONFIRM_ROUTE = '/confirm';
const BLOG_ROUTE = '/blog';
const ABOUT_US_ROUTE = '/about-us';
const COUNTER_ROUTE = '/counter';
const ACCESS_DENIED_ROUTE = '/access-denied';
const RESTAURANT_ADMIN_HOME_ROUTE = '/HomePageRestaurant';
const RESTAURANT_ADMIN_ALL_TABLE_BOOKING_ROUTE = '/manage/all-table-booking';
const HOME_ROUTE = '/';

export {
  RESTAURANT_DETAIL_ROUTE,
  RESTAURANT_ROUTE as RESTAURANT,
  USER_ROUTE as USER,
  USER_PASS_ROUTE as USER_PASS,
  USER_FAVOR_ROUTE as USER_FAVOR,
  SIGN_IN_ROUTE as SIGN_IN,
  SIGN_UP_ROUTE as SIGN_UP,
  CONFIRM_ROUTE as CONFIRM,
  BLOG_ROUTE as BLOG,
  ABOUT_US_ROUTE as ABOUT_US,
  COUNTER_ROUTE as COUNTER,
  ACCESS_DENIED_ROUTE as ACCESS_DENIED,
  RESTAURANT_ADMIN_HOME_ROUTE as RESTAURANT_ADMIN_HOME,
  RESTAURANT_ADMIN_ALL_TABLE_BOOKING_ROUTE as RESTAURANT_ADMIN_ALL_TABLE_BOOKING,
  HOME_ROUTE as HOME,
};
