const RESTAURANT_DETAIL_ROUTE = '/restaurant-detail/:id';
const RESTAURANT_ROUTE = '/restaurant';
const USER_ROUTE = '/user';
const USER_PASS_ROUTE = '/user-pass';
const USER_FAVOR_ROUTE = '/user-favorite';
const SIGN_IN_ROUTE = '/signin';
const BOOKING_HISTORY = '/history';
const SIGN_UP_ROUTE = '/signup';
const CONFIRM_ROUTE = '/confirm';
const BLOG_ROUTE = '/blog';
const ABOUT_US_ROUTE = '/about-us';
const COUNTER_ROUTE = '/counter';
const ACCESS_DENIED_ROUTE = '/access-denied';
const RESTAURANT_ADMIN_HOME_ROUTE = '/manage/home';
const RESTAURANT_ADMIN_ALL_TABLE_BOOKING_ROUTE = '/manage/all-table-booking';
const RESTAURANT_ADMIN_DETAIL_TABLE_BOOKING_ROUTE =
  '/manage/detail-table-booking/:id';
const HOME_ROUTE = '/';
const SUCCESSS_ROUTE = '/success';
const PAYMENT_ROUTE = '/payment';
const RESTAURANT_ADMIN_MANAGE_FOOD_ROUTE = '/manage/food';
const RESTAURANT_ADMIN_INFO_ROUTE = '/manage/info';
const RESTAURANT_FEEDBACK_ROUTE = '/manage/feedback';
const RESTAURANT_ADMIN_MANAGE_FEES_ROUTE = '/manage/fees';
const RESTAURANT_ADMIN_REPORT_BOOKING_TABLE_ROUTE = '/manage/report';
const RESTAURANT_ADMIN_MANAGE_BOOKING_TABLE_ONLINE_ROUTE = '/manage/online';
const RESTAURANT_ADMIN_MANAGE_ADVERTISEMENT_ROUTE = '/manage/advertisement';

export {
  BOOKING_HISTORY,
  RESTAURANT_DETAIL_ROUTE,
  RESTAURANT_ROUTE,
  USER_ROUTE,
  USER_PASS_ROUTE,
  USER_FAVOR_ROUTE,
  SIGN_IN_ROUTE,
  SIGN_UP_ROUTE,
  CONFIRM_ROUTE,
  BLOG_ROUTE,
  ABOUT_US_ROUTE,
  COUNTER_ROUTE,
  ACCESS_DENIED_ROUTE,
  RESTAURANT_ADMIN_HOME_ROUTE,
  RESTAURANT_ADMIN_ALL_TABLE_BOOKING_ROUTE,
  HOME_ROUTE,
  SUCCESSS_ROUTE,
  PAYMENT_ROUTE,
  RESTAURANT_ADMIN_DETAIL_TABLE_BOOKING_ROUTE,
  RESTAURANT_ADMIN_MANAGE_FOOD_ROUTE,
  RESTAURANT_ADMIN_INFO_ROUTE,
  RESTAURANT_FEEDBACK_ROUTE,
  RESTAURANT_ADMIN_MANAGE_FEES_ROUTE,
  RESTAURANT_ADMIN_REPORT_BOOKING_TABLE_ROUTE,
  RESTAURANT_ADMIN_MANAGE_BOOKING_TABLE_ONLINE_ROUTE,
  RESTAURANT_ADMIN_MANAGE_ADVERTISEMENT_ROUTE,
};
